/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { initializeApp, getApps, FirebaseApp } from 'firebase/app';
import { 
  getFirestore, 
  collection, 
  doc, 
  setDoc, 
  deleteDoc,
  onSnapshot, 
  getDocs, 
  writeBatch,
  Firestore,
  Unsubscribe
} from 'firebase/firestore';
import { Student, Teacher, SavedPin } from '../types';

let app: FirebaseApp | null = null;
let db: Firestore | null = null;
let isFirebaseInitialized = false;

// Attempt to load Firebase configuration dynamically from /firebase-applet-config.json
// or fallback to predefined environment variables
export async function initFirebaseService(onReady: (active: boolean) => void) {
  try {
    // Check environment variables first
    const metaEnv = (import.meta as any).env || {};
    const envConfig = {
      apiKey: metaEnv.VITE_FIREBASE_API_KEY,
      authDomain: metaEnv.VITE_FIREBASE_AUTH_DOMAIN,
      projectId: metaEnv.VITE_FIREBASE_PROJECT_ID,
      storageBucket: metaEnv.VITE_FIREBASE_STORAGE_BUCKET,
      messagingSenderId: metaEnv.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: metaEnv.VITE_FIREBASE_APP_ID,
    };

    let finalConfig: any = null;

    if (envConfig.apiKey && envConfig.projectId) {
      finalConfig = envConfig;
    } else {
      // Try to fetch public/firebase-applet-config.json which is generated by the AI Studio platform
      const response = await fetch('/firebase-applet-config.json');
      if (response.ok) {
        finalConfig = await response.json();
      }
    }

    if (finalConfig && finalConfig.apiKey && finalConfig.projectId) {
      if (getApps().length === 0) {
        app = initializeApp(finalConfig);
      } else {
        app = getApps()[0];
      }
      
      // Use custom firestore database ID if specified in configuration
      if (finalConfig.firestoreDatabaseId) {
        db = getFirestore(app, finalConfig.firestoreDatabaseId);
      } else {
        db = getFirestore(app);
      }
      
      isFirebaseInitialized = true;
      console.log('Firebase synced and initialized successfully on port 3000');
      onReady(true);
      return true;
    }
  } catch (error) {
    console.warn('Firebase setup is pending or in Local Fallback mode:', error);
  }
  
  isFirebaseInitialized = false;
  onReady(false);
  return false;
}

export function isFirebaseReady(): boolean {
  return isFirebaseInitialized && db !== null;
}

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId: string | null;
  };
}

function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: 'anonymous'
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

/**
 * Sync Students collection in real-time
 */
export function subscribeToStudents(onUpdate: (students: Student[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'students'), (snapshot) => {
    const list: Student[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as Student);
    });
    onUpdate(list);
  }, (error) => {
    handleFirestoreError(error, OperationType.LIST, 'students');
  });
}

/**
 * Sync Teachers collection in real-time
 */
export function subscribeToTeachers(onUpdate: (teachers: Teacher[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'teachers'), (snapshot) => {
    const list: Teacher[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as Teacher);
    });
    onUpdate(list);
  }, (error) => {
    handleFirestoreError(error, OperationType.LIST, 'teachers');
  });
}

/**
 * Sync Authorized PINs collection in real-time
 */
export function subscribeToPins(onUpdate: (pins: SavedPin[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'pins'), (snapshot) => {
    const list: SavedPin[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as SavedPin);
    });
    onUpdate(list);
  }, (error) => {
    handleFirestoreError(error, OperationType.LIST, 'pins');
  });
}

/**
 * CRUD functions for Students
 */
export async function dbSaveStudent(student: Student) {
  if (!db) return false;
  try {
    await setDoc(doc(db, 'students', student.id), student);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `students/${student.id}`);
    return false;
  }
}

export async function dbDeleteStudent(id: string) {
  if (!db) return false;
  try {
    await deleteDoc(doc(db, 'students', id));
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `students/${id}`);
    return false;
  }
}

/**
 * CRUD functions for Teachers
 */
export async function dbSaveTeacher(teacher: Teacher) {
  if (!db) return false;
  try {
    await setDoc(doc(db, 'teachers', teacher.id), teacher);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `teachers/${teacher.id}`);
    return false;
  }
}

export async function dbDeleteTeacher(id: string) {
  if (!db) return false;
  try {
    await deleteDoc(doc(db, 'teachers', id));
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `teachers/${id}`);
    return false;
  }
}

/**
 * CRUD functions for PINs
 */
export async function dbSavePin(pin: SavedPin) {
  if (!db) return false;
  try {
    await setDoc(doc(db, 'pins', pin.id), pin);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `pins/${pin.id}`);
    return false;
  }
}

export async function dbDeletePin(id: string) {
  if (!db) return false;
  try {
    await deleteDoc(doc(db, 'pins', id));
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `pins/${id}`);
    return false;
  }
}

/**
 * One-time data uploading (Migration from localStorage to Cloud Firestore)
 */
export async function uploadLocalDataToFirebase(students: Student[], teachers: Teacher[], pins: SavedPin[]) {
  if (!db) return false;
  try {
    const batch = writeBatch(db);
    
    // Migrate students
    for (const s of students) {
      const docRef = doc(db, 'students', s.id);
      batch.set(docRef, s);
    }
    
    // Migrate teachers
    for (const t of teachers) {
      const docRef = doc(db, 'teachers', t.id);
      batch.set(docRef, t);
    }

    // Migrate pins
    for (const p of pins) {
      const docRef = doc(db, 'pins', p.id);
      batch.set(docRef, p);
    }
    
    await batch.commit();
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, 'batch-migration');
    return false;
  }
}
