/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { initializeApp, getApps, FirebaseApp } from 'firebase/app';
import { 
  getFirestore, 
  collection, 
  doc, 
  setDoc, 
  deleteDoc,
  onSnapshot, 
  getDocs, 
  writeBatch,
  Firestore,
  Unsubscribe
} from 'firebase/firestore';
import { Student, Teacher, SavedPin } from '../types';

let app: FirebaseApp | null = null;
let db: Firestore | null = null;
let isFirebaseInitialized = false;

// Attempt to load Firebase configuration dynamically from /firebase-applet-config.json
// or fallback to predefined environment variables
export async function initFirebaseService(onReady: (active: boolean) => void) {
  try {
    // Check environment variables first
    const metaEnv = (import.meta as any).env || {};
    const envConfig = {
      apiKey: metaEnv.VITE_FIREBASE_API_KEY,
      authDomain: metaEnv.VITE_FIREBASE_AUTH_DOMAIN,
      projectId: metaEnv.VITE_FIREBASE_PROJECT_ID,
      storageBucket: metaEnv.VITE_FIREBASE_STORAGE_BUCKET,
      messagingSenderId: metaEnv.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: metaEnv.VITE_FIREBASE_APP_ID,
    };

    let finalConfig: any = null;

    if (envConfig.apiKey && envConfig.projectId) {
      finalConfig = envConfig;
    } else {
      // Try to fetch public/firebase-applet-config.json which is generated by the AI Studio platform
      const response = await fetch('/firebase-applet-config.json');
      if (response.ok) {
        finalConfig = await response.json();
      }
    }

    if (finalConfig && finalConfig.apiKey && finalConfig.projectId) {
      if (getApps().length === 0) {
        app = initializeApp(finalConfig);
      } else {
        app = getApps()[0];
      }
      
      // Use custom firestore database ID if specified in configuration
      if (finalConfig.firestoreDatabaseId) {
        db = getFirestore(app, finalConfig.firestoreDatabaseId);
      } else {
        db = getFirestore(app);
      }
      
      isFirebaseInitialized = true;
      console.log('Firebase synced and initialized successfully on port 3000');
      onReady(true);
      return true;
    }
  } catch (error) {
    console.warn('Firebase setup is pending or in Local Fallback mode:', error);
  }
  
  isFirebaseInitialized = false;
  onReady(false);
  return false;
}

export function isFirebaseReady(): boolean {
  return isFirebaseInitialized && db !== null;
}

/**
 * Sync Students collection in real-time
 */
export function subscribeToStudents(onUpdate: (students: Student[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'students'), (snapshot) => {
    const list: Student[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as Student);
    });
    // Sort students by name or id if desired
    onUpdate(list);
  }, (error) => {
    console.error('Error fetching students snapshot:', error);
  });
}

/**
 * Sync Teachers collection in real-time
 */
export function subscribeToTeachers(onUpdate: (teachers: Teacher[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'teachers'), (snapshot) => {
    const list: Teacher[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as Teacher);
    });
    onUpdate(list);
  }, (error) => {
    console.error('Error fetching teachers snapshot:', error);
  });
}

/**
 * Sync Authorized PINs collection in real-time
 */
export function subscribeToPins(onUpdate: (pins: SavedPin[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'pins'), (snapshot) => {
    const list: SavedPin[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as SavedPin);
    });
    onUpdate(list);
  }, (error) => {
    console.error('Error fetching PINs snapshot:', error);
  });
}

/**
 * CRUD functions for Students
 */
export async function dbSaveStudent(student: Student) {
  if (!db) return false;
  await setDoc(doc(db, 'students', student.id), student);
  return true;
}

export async function dbDeleteStudent(id: string) {
  if (!db) return false;
  await deleteDoc(doc(db, 'students', id));
  return true;
}

/**
 * CRUD functions for Teachers
 */
export async function dbSaveTeacher(teacher: Teacher) {
  if (!db) return false;
  await setDoc(doc(db, 'teachers', teacher.id), teacher);
  return true;
}

export async function dbDeleteTeacher(id: string) {
  if (!db) return false;
  await deleteDoc(doc(db, 'teachers', id));
  return true;
}

/**
 * CRUD functions for PINs
 */
export async function dbSavePin(pin: SavedPin) {
  if (!db) return false;
  await setDoc(doc(db, 'pins', pin.id), pin);
  return true;
}

export async function dbDeletePin(id: string) {
  if (!db) return false;
  await deleteDoc(doc(db, 'pins', id));
  return true;
}

/**
 * One-time data uploading (Migration from localStorage to Cloud Firestore)
 */
export async function uploadLocalDataToFirebase(students: Student[], teachers: Teacher[], pins: SavedPin[]) {
  if (!db) return false;
  const batch = writeBatch(db);
  
  // Migrate students
  for (const s of students) {
    const docRef = doc(db, 'students', s.id);
    batch.set(docRef, s);
  }
  
  // Migrate teachers
  for (const t of teachers) {
    const docRef = doc(db, 'teachers', t.id);
    batch.set(docRef, t);
  }

  // Migrate pins
  for (const p of pins) {
    const docRef = doc(db, 'pins', p.id);
    batch.set(docRef, p);
  }
  
  await batch.commit();
  return true;
}
